name: eks test
on:
    workflow_dispatch

jobs:
    eks_test:
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: initial look
              run: ls
            - name: assume role
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::884348119369:role/eks-tester-role
            - name: try to get token
              run: aws eks get-token --cluster-name serious-classical-dinosaur | jq -r '.status' > output_file.txt
            - name: look around
              run: ls
            - name: inspect da file
              run: cat output_file.txt
            - name: try assume from file
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::884348119369:role/role-for-eks-to-assume
                web-identity-token-file: output_file.txt
                retry-max-attempts: 4
            - name: verify creds
              run: aws sts get-caller-identity
