name: http proxy test
on: 
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    proxy-test:
        runs-on: ubuntu-latest
        steps:
          - name: clone repo
            uses: actions/checkout@v4
          - name: install tinyproxy
            run: |
              sudo apt-get update
              sudo apt-get install tinyproxy
          - name: start tinyproxy
            run: sudo tinyproxy -c tinyproxy.conf
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4.3.1
            with:
              aws-region: us-east-1
              role-to-assume: arn:aws:iam::884348119369:role/first-role-to-test
              http-proxy: http://127.0.0.1:9999
          - name: checkout logs 
            run: sudo cat whatever.txt
          - name: check logs to see if successful call
            run: sudo grep -q "Request" whatever.txt && echo "FOO=1" >> $GITHUB_ENV || echo "FOO=0" >> $GITHUB_ENV
          - name: fail job if bad call 
            if: ${{ env.FOO }} != 1
            run: exit 1

