name: http proxy test
on: 
    workflow_dispatch:

permissions:
    contents: read

jobs:
    proxy-test:
        runs-on: ubuntu-latest
        steps:
          - name: clone repo
            uses: actions/checkout@v4
          - name: install tinyproxy
            run: |
              sudo apt-get update
              sudo apt-get install tinyproxy
          - name: start tinyproxy
            run: tinyproxy -d -c tinyproxy.conf
          - name: hit da proxy
            run: http_proxy=127.0.0.1:8888 curl example.com