name: iam user test
on: 
    workflow_dispatch:

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
            aws-region: us-east-1
            aws-access-key-id: ${{ secrets.USER_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.USER_SECRET_ACCESS_KEY }}
      - name: Get Caller Identity
        run: |
          aws sts get-caller-identity
