name: inline policy experiments
on: 
    workflow_dispatch:

permissions:
    id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: scoped down policy
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with: 
            aws-region: us-east-2
            role-to-assume: arn:aws:iam::884348119369:role/cawsc-inline-policy-test
      - name: list buckets
        run: |
          aws s3 ls
      - name: try to list bucket contents
        id: bucketContentsStep
        continue-on-error: true
        run: |
          aws s3 ls s3://lehmanmj-cawsc-test-1
      - name: fail if last step succeeded
        if: steps.bucketContentsStep.outcome == 'success'
        run: exit 1
        

