name: oidc role chain
on: 
    workflow_dispatch:

permissions:
    id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::884348119369:role/first-role-to-test
      - name: Get Caller Identity
        run: |
          aws sts get-caller-identity
      - name: assume second role
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
            aws-region: us-east-2
            role-to-assume: arn:aws:iam::884348119369:role/second-role-to-test
            role-chaining: true
            role-skip-session-tagging: true
      - name: get caller identity
        run: |
          aws sts get-caller-identity