name: clean-up-inputs
on: 
    workflow_dispatch:

# Need ID token write permission to use OIDC
permissions:
  id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@6092b743408cc71497ede52295e24a6166e86cfb
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Get Caller Identity
        run: |
          aws sts get-caller-identity
